version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
 
    ports:
       - 4306:3306
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      -  .:/code
    ports:
      - "8000:8000"
    depends_on:
      -  db